import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../app/component/header";
import Footer from "../app/component/footer";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      
      <body
      
    
      >
        <Header />
        {children}
        
        <Footer />
     </body>
      
    </html>
  );
}
